site_name: Docs
site_url: https://docs.microrack.org
site_description: User guides and documentation for MICRORACK modular synthesizer system
site_author: MICRORACK

repo_name: microrack/docs
repo_url: https://github.com/microrack/docs-test

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/microrack.synth
      name: Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/microrack.synth
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/microrack
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/microrack_synth
      name: Twitter / X
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@microrack-modular-synth
      name: YouTube
  generator: false

extra_css:
  - assets/extra.css

copyright: Copyright &copy; 2019-2025 MICRORACK Inc

nav:
  - About: index.md
  - Getting Started:
    - Introduction: getting-started/index.md
    - First Steps: getting-started/first-steps.md
    - Setup: getting-started/setup.md
  - Modules:
    - Overview: modules/index.md
    - mod-vco: modules/mod-vco/README.md
    - mod-noise: modules/mod-noise/README.md
    - mod-vcf: modules/mod-vcf/README.md
    - mod-delay: modules/mod-delay/README.md
    - mod-eq: modules/mod-eq/README.md
    - mod-comp: modules/mod-comp/README.md
    - mod-sat: modules/mod-sat/README.md
    - mod-lpg: modules/mod-lpg/README.md
    - mod-env: modules/mod-env/README.md
    - mod-lfo: modules/mod-lfo/README.md
    - mod-seq: modules/mod-seq/README.md
    - mod-mix: modules/mod-mix/README.md
    - mod-clk: modules/mod-clk/README.md
    - mod-key: modules/mod-key/README.md
    - mod-in-63: modules/mod-in-63/README.md
    - mod-out-35: modules/mod-out-35/README.md
    - mod-out-63: modules/mod-out-63/README.md
    - mod-midi: modules/mod-midi/README.md
    - mod-jacket: modules/mod-jacket/README.md
  - Specification:
    - Overview: specification/index.md
    - Mechanical: specification/mechanical.md
    - Electronical: specification/electronical.md
  - Ecosystem:
    - Overview: ecosystem/index.md
    - Power: ecosystem/power.md
    - I/O: ecosystem/io.md
    - Chassis: ecosystem/chassis.md
    - Chaining: ecosystem/chaining.md
    - Compatibility: ecosystem/compatibility.md
    - Use Cases: ecosystem/use-cases.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Bass Patch: tutorials/bass-patch.md
    - Ambient Pad: tutorials/ambient-pad.md
  - User Guide:
    - Overview: user-guide/index.md
    - Patching Techniques: user-guide/patching-techniques.md
    - Sound Design: user-guide/sound-design.md
